# Generated by Django 5.0.7 on 2024-12-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_capaprincipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo da imagem')),
                ('imagem', models.FileField(blank=True, null=True, upload_to=django.db.models.deletion.CASCADE, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
            },
        ),
    ]
