# Generated by Django 5.0.7 on 2024-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0005_publicacoes_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='img_capa',
            field=models.FileField(blank=True, null=True, upload_to='static/imagens', verbose_name='Imagem de Capa'),
        ),
    ]
